### PR TITLE
Update docker.yml

### PR DESCRIPTION
**Pull request by benchonaut**
make it multiarch

Ticket Ref #47

### CODE REVIEW

**Comment by muety** [comment]
I'm not too familiar with GitHub actions or Docker's multi-platform support. Can you explain this, please? When specifying `linux/arm64/v8` for example, will the image be built on an ARM64 machine and thus the contained Telepush binary will be compiled for ARM64 as well?

**Comment by benchonaut** [comment]
will be built for `PLATFORMS: "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8"`

( /386 might fail with many ubuntu's as base image , but with go it should work )

some reference examples:


* multi-arch , multi-registry: https://github.com/thefoundation-builder/hugo-extended-webmentions/tree/main/.github/workflows

* multi-arch with baseimage: https://github.com/thefoundation-builder/remark42-rootless/tree/main/.github/workflows

* using gh-actions "matrix" for architecture:  https://github.com/thefoundation-builder/hardened-dropbear-builder/blob/main/.github/workflows/builder.yml

* integrated buildx multi-stage with gh-actions "matrix" for architecture: https://github.com/thefoundation-builder/hocker-builder-github/tree/main/.github/workflows


regards

**Comment by muety** [comment]
Did you try this? Will Telepush inside an `arm64/v8` image (for example) actually start up on an according machine? Not only the container, but also the actual executable itself?

Also, I think `386` and `arm/v6` are not needed anymore.

**Comment by benchonaut** [comment]
I did it on other projects ( also in go ) , the 4 references are also from me , so before asking " but also the actual executable itself" , maybe read about buildx , it uses a virtual machine per container arch .. so each arch container will be native "single arch" , and the buildx process pushes a manifest to registry ( so it will look like the screenshot above )

**Pull request closed without merging**
